version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  labels:
  - dependencies
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
