version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  target-branch: dev
  labels:
  - dependencies
  versioning-strategy: increase
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: dev
  commit-message:
    prefix: ci
    prefix-development: chore
    include: scope
