pull_request_rules:
  - name: merge PRs labeled ready-to-merge
    conditions:
      - status-success=Finish Test
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        strict_method: merge
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      label:
        remove:
          - ready-to-merge
      delete_head_branch:
