queue_rules:
  - name: duplicated default from merge PRs labeled ready-to-merge
    queue_conditions:
      - status-success=Finish Test
      - label=ready-to-merge
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Finish Test
    merge_method: squash
  - name: duplicated default from Merge staged release
    queue_conditions:
      - check-success=Finish Test
      - head=release-staging
      - approved-reviews-by=donmahallem
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Finish Test
    merge_method: squash

pull_request_rules:
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(main|master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      label:
        remove:
          - ready-to-merge
      delete_head_branch:
  - name: rebase ready-to-merge branches
    conditions:
      - label = ready-to-merge
    actions:
      rebase:
  - name: Merge staged release + merge PRs labeled ready-to-merge
    conditions: []
    actions:
      queue:
priority_rules:
  - name: priority for queue `duplicated default from merge PRs labeled ready-to-merge`
    conditions:
      - status-success=Finish Test
      - label=ready-to-merge
    priority: 2250
