pull_request_rules:
  - name: automatic merge dependabot PRs into dev
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Finish Test
      - base=dev
    actions:
      comment:
        message: "@dependabot squash and merge"
  - name: merge PRs labeled ready-to-merge
    conditions:
      - status-success=Finish Test
      - label=ready-to-merge
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        strict_method: rebase
      label:
        remove:
          - ready-to-merge
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      delete_head_branch:
  - name: label pull requests ci if in workflows
    conditions:
      - merged
      - -head~=^(master|dev)$
      - files~=^\.github/workflows
    actions:
      label:
        add:
          - ci
