# This is an example Mocha config containing every Mocha option plus others
allow-uncaught: false
async-only: false
bail: false
check-leaks: true
color: true
delay: false
diff: true
exit: false # could be expressed as "no-exit: true"
extension:
  - ts
# fgrep and grep are mutually exclusive
# fgrep: something
forbid-only: false
forbid-pending: false
full-trace: false
# fgrep and grep are mutually exclusive
# grep: something
growl: false
inline-diffs: false
# needs to be used with grep or fgrep
# invert: false
# opts: './test/.mocha.opts'
package: './package.json'
recursive: true
reporter: spec
require: 'ts-node/register'
retries: 1
slow: 75
sort: false
spec: src/**/*.spec.ts # the positional arguments!
ui: bdd
watch: false