comment:
  layout: "reach, diff, flags, files"
coverage:
  status:
    project:
      api-types:
        paths:
          - packages/api-types/*
flags:
  api-types:
    paths:
      - packages/api-types/
