name: Create PR into master
on:
  push:
    branches:
    - dev  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    name: Optionally create Pull Request
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"                      # If blank, default: master
        pr_title: "chore: merge dev into master" # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_reviewer: "donmahallem"                         # Comma-separated list (no spaces)
        pr_assignee: "donmahallem"                         # Comma-separated list (no spaces)
        pr_allow_empty: false                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}
