name: Test
on: [push,pull_request]

jobs:
  test_suite:
    runs-on: ${{ matrix.os }}
    name: Test - ${{ matrix.os }} - Node ${{ matrix.node }}
    timeout-minutes: 30
    strategy:
      matrix:
        node: [10, 12, 14]
        #os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Run Build
        run: npm run build
      - name: Run Test
        run: npm run test:coverage --no-sort
      - name: Merge Test Reports
        run: npm run coverage:merge
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: ${{ matrix.os }}_node${{ matrix.node }}
          parallel: true
      - name: Run Lint
        run: npm run lint --no-sort
      - name: Run Docs
        run: npm run docs --no-sort
  finish:
    needs: test_suite
    name: Finish Test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
