name: Create Releases
on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [master]

jobs:
  build_suite:
    runs-on: ${{ matrix.os }}
    name: Version Release
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        node: [ 16]
        os: [ubuntu-latest] #, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref:  ${{ github.event.workflow_run.head_branch }}
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install Deps
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Run Build
        run: npx lerna run build
      - name: Setup GIT
        run: |
          git config --local user.email "donmahallem@users.noreply.github.com"
          git config --local user.name "donmahallem"
      - name: Version Packages
        run: npx lerna version --create-release github -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - uses: connor-baer/action-sync-branch@main
        with:
          branch: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          force: false

  release_npm:
    needs: [build_suite]
    runs-on: ubuntu-latest
    name: Publish Package to NPM
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          ref:  ${{ github.event.workflow_run.head_branch }}
      - name: Fetch Tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install Packages
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Build Package
        run: npm run build
      - name: Prepare Package
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish Packages
        run: npx lerna publish from-git -y --no-verify-access
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  release_github:
    needs: [build_suite]
    runs-on: ubuntu-latest
    name: Publish Package to GITHUB
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          ref:  ${{ github.event.workflow_run.head_branch }}
      - name: Fetch Tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: Install Packages
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Build Package
        run: npm run build
      - name: Prepare Package
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Packages
        run: npx lerna publish from-package -y --no-verify-access --registry https://npm.pkg.github.com/donmahallem
